repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.11.13
    hooks:
      # Run the linter on commit
      - id: ruff
        args: [ --fix ]
      # Run the formatter on commit
      - id: ruff-format