repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.8.0
    hooks:
      # Run the linter on push (less intrusive during development)
      - id: ruff
        args: [ --fix ]
        stages: [pre-push]
      # Run the formatter on push
      - id: ruff-format
        stages: [pre-push]