name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper git testing

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Configure git for testing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Run unit tests
      run: |
        uv run pytest tests/ -v --tb=short

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper git testing

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Configure git for testing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Install GitHub CLI (for PR creation tests)
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh

    - name: Run integration tests
      run: |
        uv run pytest tests/test_status_only.py -v --tb=short

  mutation-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper git testing

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra test

    - name: Configure git for testing
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Cache mutation testing
      uses: actions/cache@v4
      with:
        path: mutants.sqlite
        key: cosmic-ray-${{ hashFiles('src/**/*.py', 'tests/**/*.py', 'pyproject.toml') }}

    - name: Run mutation testing with cosmic-ray
      run: |
        # Initialize cosmic-ray database if it doesn't exist
        if [ ! -f mutants.sqlite ]; then
          uv run cosmic-ray init mutants.toml mutants.sqlite
        fi
        
        # Run cosmic-ray mutation testing
        uv run cosmic-ray exec mutants.toml mutants.sqlite
        
        echo "## Mutation Testing Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        # Count total mutations and results
        TOTAL=$(uv run cosmic-ray dump mutants.sqlite | wc -l || echo "0")
        KILLED=$(uv run cosmic-ray dump mutants.sqlite | grep -c '"outcome": "killed"' || echo "0") 
        SURVIVED=$(uv run cosmic-ray dump mutants.sqlite | grep -c '"outcome": "survived"' || echo "0")
        echo "Total mutations: $TOTAL" >> $GITHUB_STEP_SUMMARY
        echo "Killed: $KILLED" >> $GITHUB_STEP_SUMMARY  
        echo "Survived: $SURVIVED" >> $GITHUB_STEP_SUMMARY
        if [ "$TOTAL" -gt 0 ]; then
          SCORE=$(python3 -c "print(f'{$KILLED * 100 / $TOTAL:.1f}')" 2>/dev/null || echo "0")
          echo "Mutation score: ${SCORE}%" >> $GITHUB_STEP_SUMMARY
        fi
        echo '```' >> $GITHUB_STEP_SUMMARY
      continue-on-error: true  # Don't fail the build if mutation score is low

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Check code formatting with ruff
      run: |
        uv run ruff format --check .

    - name: Lint with ruff
      run: |
        uv run ruff check .

    - name: Check Python syntax
      run: |
        uv run python -m py_compile src/vibe_git/*.py tests/*.py